name: clap
task: state

instance:
  _target_: tsseg.algorithms.clap.clap_detector.ClapDetector

  #semi_supervised: false # Switch to true for exact semi-supervised mode (uses change point list instead of actual change points)
  n_segments: null
  n_change_points: null # Explicit addition for the pipeline
  window_size: "suss"
  classifier: "rocket"
  merge_score: "cgain"
  n_splits: 5
  n_jobs: 1
  sample_size: 1000
  random_state: 0
  change_points: null

tunable_parameters:
  - window_size: ["suss", "fft", "acf"]
  - classifier: ["rocket", "mrhydra"]