name: e2usd
task: state

instance:
  _target_: tsseg.algorithms.e2usd.detector.E2USDDetector

  axis: 0
  window_size: 256
  step: 50
  n_states: 20 # Overriden with GT in semi_supervised mode
  alpha: 1e3
  batch_size: 1
  nb_steps: 20
  lr: 0.003
  depth: 1
  out_channels: 4
  reduced_size: 80
  kernel_size: 3
  use_gpu: null
  random_state: 0

tunable_parameters:
  - window_size: [64, 128, 256]
  - step: [20, 50, 100]