name: espresso
task: change_point

instance:
  _target_: tsseg.algorithms.espresso.detector.EspressoDetector

  window_size: 64 # can be set using autocorrelation/FFT on periodic data
  chain_len: 3
  n_segments: null
  peak_distance_fraction: 0.01
  axis: 0
  random_state: 0

tunable_parameters:
 - window_size: [32, 64, 128]
 - chain_len: [1, 3, 5]