name: hdp-hsmm-legacy
task: state

instance:
  _target_: tsseg.algorithms.hdp_hsmm.legacy_detector.HdpHsmmLegacyDetector
  
  axis: 0
  alpha: 1.0
  beta: 1.0
  n_iter: 20
  n_max_states: 60

tunable_parameters:
  - alpha: [1.0, 3.0, 6.0]
  - beta: [1.0, 3.0, 6.0]
  #- n_iter : [20, 50]