name: hdp-hsmm
task: state

instance:
  _target_: tsseg.algorithms.hdp_hsmm.detector.HdpHsmmDetector

  axis: 0
  alpha: 6.0
  gamma: 6.0
  init_state_concentration: 6.0
  n_iter: 20
  n_max_states: 20
  trunc: 100
  kappa0: 0.25
  nu0: null
  prior_mean: 0.0
  prior_scale: 1.0
  dur_alpha: 2.0
  dur_beta: 0.1

tunable_parameters:
  - alpha: [1.0, 3.0, 6.0]
  - gamma: [1.0, 3.0, 6.0]
  #- n_iter : [20, 50]