name: hidalgo
task: state

instance:
  _target_: tsseg.algorithms.hidalgo.detector.HidalgoDetector

  metric: "euclidean"
  K_states: 2
  zeta: 0.8
  q: 3
  n_iter: 1000
  n_replicas: 1
  burn_in: 0.9
  fixed_Z: false
  use_Potts: true
  estimate_zeta: false
  sampling_rate: 10
  a: null
  b: null
  c: null
  f: null

tunable_parameters:
  - K_states: [2, 5, 10]
  - zeta: [0.5, 0.8, 1.0]
  - n_iter: [100, 1000]