# @package _global_

defaults:
  - _self_
  - experiment: supervised
  - algorithm: time2state
  - dataset: mocap
  - metric: default
  - preprocessing: default
  - override hydra/sweeper: basic
  - override hydra/launcher: basic # Change for submitit_slurm  on server / basic for local runs

# Default configuration for Hydra
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}