# @package _global_

defaults:
  - _self_
  - pipeline: default              # Comment to debug
  - experiment: unsupervised
  - algorithm: time2state
  - dataset: mocap
  - metric: default
  - preprocessing: default
  - override hydra/sweeper: basic
  - override hydra/launcher: basic # Change for submitit_slurm  on server / basic for local runs

# mlflow:
#   tracking_uri: ${oc.env:MLFLOW_TRACKING_URI, "http://cleps:15050"}

# Default configuration for Hydra
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  # job:
  #   env_set:
  #     MLFLOW_TRACKING_URI: http://cleps:15050