defaults:
  - /config
  - /algorithm: time2state
  - /dataset: mocap
  - _self_

hydra:
  sweeper:
    params:
      algorithm.win_size: 128,256
      algorithm.lr: 0.001,0.003
      algorithm.depth: 8,10